Fix tikv config check failure on deploy (#1306) (#1307)
Fix tikv config check failure on deploy due to wrong format of config template:
```
[TiKV1-1]: Ansible Failed! ==>
  changed=true
  cmd: cd /tmp/tidb_check_config && ./tikv-server --pd-endpoints pd:port --config ./tikv.toml --config-check
  delta: '0:00:00.524112'
  end: '2020-05-25 14:35:13.870777'
  msg: non-zero return code
  rc: 101
  start: '2020-05-25 14:35:13.346665'
  stderr: |-
    thread 'main' panicked at 'invalid auto generated configuration file ./tikv.toml, err missing field `type` for key `security.encryption.master-key`', /rustc/b2e36e6c2d229126b59e892c9147fbb68115d292/src/libstd/macros.rs:16:9
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  stderr_lines:
  - thread 'main' panicked at 'invalid auto generated configuration file ./tikv.toml, err missing field `type` for key `security.encryption.master-key`', /rustc/b2e36e6c2d229126b59e892c9147fbb68115d292/src/libstd/macros.rs:16:9
  - 'note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace'
  stdout: ''
  stdout_lines: <omitted>
``` 

The is because the `type` field of `[security.encryption.master-key]` is required if the table header presents.

Signed-off-by: Yi Wu <yiwu@pingcap.com>